spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation?serverTimezone=GMT%2B8
    username: root
    password: jingsai0818
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false